logging:
  project_name: "EFVFL"
  experiment_name: "modelnet10-cvfl-4b"

data:
  module_path: "data.modelnet10"
  module_name: "ModelNet10DataModule"
  params:
    data_dir: "../data"
    num_workers: 8
    batch_size: 128

model:
  module_path: "models.modelnet_model"
  module_name: "CNNSplitNN"
  params:
    dataset: "modelnet10"
    num_clients: 12
    cut_size: 16
    aggregation_mechanism: "conc"
    num_classes: 10
    private_labels: false
    optimizer: "sgd"
    lr: 0.064
    momentum: 0.0
    weight_decay: 0.001
    scheduler: "cosine_annealing_lr"
    eta_min_ratio: 0.1
    compression_type: "direct"
    compressor: "qsgd"
    compression_parameter: 4
    compute_grad_sqd_norm: false

trainer:
  max_epochs: 150
