logging:
  project_name: "EFVFL"
  experiment_name: "cifar100-cvfl-0.1k"

data:
  module_path: "data.cifar100"
  module_name: "CIFAR100DataModule"
  params:
    data_dir: "../data"
    num_workers: 8
    batch_size: 128

model:
  module_path: "models.cifar_model"
  module_name: "ResNetSplitNN"
  params:
    dataset: "cifar100"
    num_clients: 4
    cut_size: 128
    aggregation_mechanism: "mean"
    num_classes: 100
    private_labels: false
    optimizer: "sgd"
    lr: 0.04
    momentum: 0.0
    weight_decay: 0.01
    scheduler: "cosine_annealing_lr"
    eta_min_ratio: 0.01
    compression_type: "direct"
    compressor: "topk"
    compression_parameter: 0.1
    compute_grad_sqd_norm: false

trainer:
  max_epochs: 150
